

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_lessons_with_purchase"("user_id" "uuid") RETURNS TABLE("id" "uuid", "title" "text", "description" "text", "price" numeric, "content_url" "text", "creator_id" "uuid", "created_at" timestamp with time zone, "updated_at" timestamp with time zone, "is_purchased" boolean)
    LANGUAGE "plpgsql" STABLE
    AS $$
begin
  return query
  select t.*, 
    exists (
      select 1 from purchases p 
      where p.tutorial_id = t.id and p.user_id = user_id
    ) as is_purchased
  from tutorials t;
end;
$$;


ALTER FUNCTION "public"."get_lessons_with_purchase"("user_id" "uuid") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    AS $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;


ALTER FUNCTION "public"."handle_new_user"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_lesson_and_categories"("p_lesson_id" "uuid", "p_title" "text", "p_description" "text", "p_price" numeric, "p_video_url" "text", "p_content" "jsonb", "p_thumbnail_url" "text", "p_category_ids" integer[]) RETURNS "void"
    LANGUAGE "plpgsql"
    AS $$
DECLARE
  v_old_category_ids INTEGER[];
BEGIN
  -- Update the lesson
  UPDATE tutorials
  SET 
    title = p_title,
    description = p_description,
    price = p_price,
    video_url = p_video_url,
    content = p_content,
    thumbnail_url = p_thumbnail_url,
    updated_at = NOW()
  WHERE id = p_lesson_id;

  -- Get existing category IDs
  SELECT ARRAY_AGG(category_id) INTO v_old_category_ids
  FROM tutorial_categories
  WHERE tutorial_id = p_lesson_id;

  -- Remove categories that are no longer associated
  DELETE FROM tutorial_categories
  WHERE tutorial_id = p_lesson_id
    AND category_id = ANY(v_old_category_ids)
    AND category_id != ALL(p_category_ids);

  -- Insert new category associations
  INSERT INTO tutorial_categories (tutorial_id, category_id)
  SELECT p_lesson_id, unnest(p_category_ids)
  ON CONFLICT (tutorial_id, category_id) DO NOTHING;
END;
$$;


ALTER FUNCTION "public"."update_lesson_and_categories"("p_lesson_id" "uuid", "p_title" "text", "p_description" "text", "p_price" numeric, "p_video_url" "text", "p_content" "jsonb", "p_thumbnail_url" "text", "p_category_ids" integer[]) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."update_updated_at_column"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;


ALTER FUNCTION "public"."update_updated_at_column"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tutorial_categories" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "tutorial_id" "text",
    "category_id" "text"
);


ALTER TABLE "public"."tutorial_categories" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."categories_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."categories_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."categories_id_seq" OWNED BY "public"."tutorial_categories"."id";



ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."categories_id_seq1"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."discussion_posts" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "tutorial_id" "uuid",
    "user_id" "uuid",
    "content" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "parent_id" "uuid"
);


ALTER TABLE "public"."discussion_posts" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."newsletter_subscriptions" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "email" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "public"."newsletter_subscriptions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "full_name" "text",
    "email" "text",
    "bio" "text",
    "avatar_url" "text",
    "social_media_tag" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "stripe_account_id" "text",
    "stripe_onboarding_complete" boolean DEFAULT false,
    "vimeo_access_token" "text"
);


ALTER TABLE "public"."profiles" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."purchases" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "user_id" "uuid",
    "tutorial_id" "uuid",
    "purchase_date" timestamp with time zone DEFAULT "now"(),
    "stripe_session_id" "text",
    "creator_id" "uuid",
    "amount" numeric,
    "platform_fee" numeric,
    "creator_earnings" numeric,
    "payment_intent_id" "text",
    "fee_percentage" integer,
    "status" "text",
    "metadata" "jsonb",
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."purchases" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."reviews" (
    "id" integer NOT NULL,
    "user_id" "uuid",
    "tutorial_id" "uuid",
    "rating" integer,
    "comment" "text",
    "created_at" timestamp with time zone DEFAULT "now"(),
    CONSTRAINT "reviews_rating_check" CHECK ((("rating" >= 1) AND ("rating" <= 5)))
);


ALTER TABLE "public"."reviews" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."reviews_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE "public"."reviews_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."reviews_id_seq" OWNED BY "public"."reviews"."id";



CREATE TABLE IF NOT EXISTS "public"."tutorials" (
    "id" "uuid" DEFAULT "extensions"."uuid_generate_v4"() NOT NULL,
    "title" "text" NOT NULL,
    "description" "text",
    "price" numeric(10,2),
    "vimeo_video_id" "text",
    "creator_id" "uuid" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "stripe_product_id" "text",
    "stripe_price_id" "text",
    "content" "jsonb",
    "content_url" "text",
    "thumbnail_url" "text",
    "vimeo_url" "text",
    "is_featured" boolean DEFAULT false,
    "status" "text"
);


ALTER TABLE "public"."tutorials" OWNER TO "postgres";


ALTER TABLE ONLY "public"."reviews" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."reviews_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."tutorial_categories" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."categories_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."tutorial_categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey1" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."discussion_posts"
    ADD CONSTRAINT "discussion_posts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."newsletter_subscriptions"
    ADD CONSTRAINT "newsletter_subscriptions_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."newsletter_subscriptions"
    ADD CONSTRAINT "newsletter_subscriptions_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tutorials"
    ADD CONSTRAINT "tutorials_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "unique_user_tutorial" UNIQUE ("user_id", "tutorial_id");



CREATE INDEX "idx_discussion_posts_tutorial_id" ON "public"."discussion_posts" USING "btree" ("tutorial_id");



CREATE OR REPLACE TRIGGER "update_purchases_updated_at" BEFORE UPDATE ON "public"."purchases" FOR EACH ROW EXECUTE FUNCTION "public"."update_updated_at_column"();



ALTER TABLE ONLY "public"."discussion_posts"
    ADD CONSTRAINT "discussion_posts_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."discussion_posts"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."discussion_posts"
    ADD CONSTRAINT "discussion_posts_tutorial_id_fkey" FOREIGN KEY ("tutorial_id") REFERENCES "public"."tutorials"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."discussion_posts"
    ADD CONSTRAINT "discussion_posts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON DELETE SET NULL;



ALTER TABLE ONLY "public"."tutorials"
    ADD CONSTRAINT "fk_creator" FOREIGN KEY ("creator_id") REFERENCES "public"."profiles"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_tutorial_id_fkey" FOREIGN KEY ("tutorial_id") REFERENCES "public"."tutorials"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."purchases"
    ADD CONSTRAINT "purchases_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_tutorial_id_fkey" FOREIGN KEY ("tutorial_id") REFERENCES "public"."tutorials"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."reviews"
    ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tutorials"
    ADD CONSTRAINT "tutorials_creator_id_fkey" FOREIGN KEY ("creator_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;



CREATE POLICY "Allow authenticated users to insert subscriptions" ON "public"."newsletter_subscriptions" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Allow insert own purchases" ON "public"."purchases" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Allow public access to welcome lesson" ON "public"."tutorials" FOR SELECT USING (("id" = 'e04b190b-6de5-4468-a593-b24143914489'::"uuid"));



CREATE POLICY "Allow public comments on welcome lesson" ON "public"."discussion_posts" FOR INSERT WITH CHECK (("tutorial_id" = 'e04b190b-6de5-4468-a593-b24143914489'::"uuid"));



CREATE POLICY "Allow public inserts to newsletter_subscriptions" ON "public"."newsletter_subscriptions" FOR INSERT WITH CHECK (true);



CREATE POLICY "Allow public ratings on welcome lesson" ON "public"."reviews" FOR INSERT WITH CHECK (("tutorial_id" = 'e04b190b-6de5-4468-a593-b24143914489'::"uuid"));



CREATE POLICY "Allow public read access to full_name" ON "public"."profiles" FOR SELECT USING (true);



CREATE POLICY "Allow public to view purchase counts" ON "public"."purchases" FOR SELECT USING (true);



CREATE POLICY "Allow select for authenticated users" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "Allow select own profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "Allow select own purchases" ON "public"."purchases" FOR SELECT USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Allow service role to update profiles" ON "public"."profiles" FOR UPDATE USING (("auth"."role"() = 'service_role'::"text"));



CREATE POLICY "Allow update own profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Allow update own tutorials" ON "public"."tutorials" FOR UPDATE USING (("auth"."uid"() = "creator_id"));



CREATE POLICY "Authenticated insert reviews" ON "public"."reviews" FOR INSERT WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Authenticated insert tutorials" ON "public"."tutorials" FOR INSERT WITH CHECK (("auth"."uid"() = "creator_id"));



CREATE POLICY "Creators can view purchases of their lessons" ON "public"."purchases" FOR SELECT TO "authenticated" USING (("auth"."uid"() = "creator_id"));



CREATE POLICY "Delete own profile" ON "public"."profiles" FOR DELETE USING (("auth"."uid"() = "id"));



CREATE POLICY "Enable full access for service role" ON "public"."purchases" TO "service_role" USING (true) WITH CHECK (true);



CREATE POLICY "Enable insert for users based on user_id" ON "public"."purchases" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable read access for users to their own purchases" ON "public"."purchases" FOR SELECT TO "authenticated" USING ((("auth"."uid"() = "user_id") OR ("auth"."uid"() = "creator_id")));



CREATE POLICY "Insert own profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Public select categories" ON "public"."tutorial_categories" FOR SELECT USING (true);



CREATE POLICY "Public select reviews" ON "public"."reviews" FOR SELECT USING (true);



CREATE POLICY "Public select tutorials" ON "public"."tutorials" FOR SELECT USING (true);



CREATE POLICY "Select own profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "Update own profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));



CREATE POLICY "Upsert own profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can create posts if they have access" ON "public"."discussion_posts" FOR INSERT WITH CHECK ((EXISTS ( SELECT 1
   FROM ("public"."tutorials" "t"
     LEFT JOIN "public"."purchases" "p" ON ((("p"."tutorial_id" = "t"."id") AND ("p"."user_id" = "auth"."uid"()) AND ("p"."status" = 'completed'::"text"))))
  WHERE (("t"."id" = "discussion_posts"."tutorial_id") AND (("t"."creator_id" = "auth"."uid"()) OR ("p"."id" IS NOT NULL) OR ("t"."price" = (0)::numeric))))));



CREATE POLICY "Users can delete related purchases" ON "public"."purchases" FOR DELETE TO "authenticated" USING ((("auth"."uid"() = "user_id") OR ("tutorial_id" IN ( SELECT "tutorials"."id"
   FROM "public"."tutorials"
  WHERE ("tutorials"."creator_id" = "auth"."uid"())))));



CREATE POLICY "Users can delete their own posts or if tutorial owner" ON "public"."discussion_posts" FOR DELETE USING ((("auth"."uid"() = "user_id") OR (EXISTS ( SELECT 1
   FROM "public"."tutorials" "t"
  WHERE (("t"."id" = "discussion_posts"."tutorial_id") AND ("t"."creator_id" = "auth"."uid"()))))));



CREATE POLICY "Users can delete their own profile" ON "public"."profiles" FOR DELETE TO "authenticated" USING (("id" = "auth"."uid"()));



CREATE POLICY "Users can delete their own reviews" ON "public"."reviews" FOR DELETE TO "authenticated" USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can delete their own tutorials" ON "public"."tutorials" FOR DELETE TO "authenticated" USING (("creator_id" = "auth"."uid"()));



CREATE POLICY "Users can insert their own purchases" ON "public"."purchases" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can read their own vimeo_access_token" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



CREATE POLICY "Users can update their own posts" ON "public"."discussion_posts" FOR UPDATE USING (("auth"."uid"() = "user_id"));



CREATE POLICY "Users can update their own profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can update their own vimeo_access_token" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id")) WITH CHECK (("auth"."uid"() = "id"));



CREATE POLICY "Users can view posts if they have access" ON "public"."discussion_posts" FOR SELECT USING ((EXISTS ( SELECT 1
   FROM ("public"."tutorials" "t"
     LEFT JOIN "public"."purchases" "p" ON ((("p"."tutorial_id" = "t"."id") AND ("p"."user_id" = "auth"."uid"()) AND ("p"."status" = 'completed'::"text"))))
  WHERE (("t"."id" = "discussion_posts"."tutorial_id") AND (("t"."creator_id" = "auth"."uid"()) OR ("p"."id" IS NOT NULL) OR ("t"."price" = (0)::numeric))))));



ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."discussion_posts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "insert_own_profile" ON "public"."profiles" FOR INSERT WITH CHECK (("auth"."uid"() = "id"));



ALTER TABLE "public"."newsletter_subscriptions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."purchases" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "read_own_profile" ON "public"."profiles" FOR SELECT USING (("auth"."uid"() = "id"));



ALTER TABLE "public"."reviews" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tutorial_categories" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tutorials" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "update_own_profile" ON "public"."profiles" FOR UPDATE USING (("auth"."uid"() = "id"));





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."get_lessons_with_purchase"("user_id" "uuid") TO "anon";
GRANT ALL ON FUNCTION "public"."get_lessons_with_purchase"("user_id" "uuid") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_lessons_with_purchase"("user_id" "uuid") TO "service_role";



GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "anon";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."handle_new_user"() TO "service_role";



GRANT ALL ON FUNCTION "public"."update_lesson_and_categories"("p_lesson_id" "uuid", "p_title" "text", "p_description" "text", "p_price" numeric, "p_video_url" "text", "p_content" "jsonb", "p_thumbnail_url" "text", "p_category_ids" integer[]) TO "anon";
GRANT ALL ON FUNCTION "public"."update_lesson_and_categories"("p_lesson_id" "uuid", "p_title" "text", "p_description" "text", "p_price" numeric, "p_video_url" "text", "p_content" "jsonb", "p_thumbnail_url" "text", "p_category_ids" integer[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_lesson_and_categories"("p_lesson_id" "uuid", "p_title" "text", "p_description" "text", "p_price" numeric, "p_video_url" "text", "p_content" "jsonb", "p_thumbnail_url" "text", "p_category_ids" integer[]) TO "service_role";



GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "anon";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."update_updated_at_column"() TO "service_role";


















GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON TABLE "public"."tutorial_categories" TO "anon";
GRANT ALL ON TABLE "public"."tutorial_categories" TO "authenticated";
GRANT ALL ON TABLE "public"."tutorial_categories" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."categories_id_seq1" TO "anon";
GRANT ALL ON SEQUENCE "public"."categories_id_seq1" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."categories_id_seq1" TO "service_role";



GRANT ALL ON TABLE "public"."discussion_posts" TO "anon";
GRANT ALL ON TABLE "public"."discussion_posts" TO "authenticated";
GRANT ALL ON TABLE "public"."discussion_posts" TO "service_role";



GRANT ALL ON TABLE "public"."newsletter_subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."newsletter_subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."newsletter_subscriptions" TO "service_role";
GRANT INSERT ON TABLE "public"."newsletter_subscriptions" TO PUBLIC;



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT SELECT("full_name") ON TABLE "public"."profiles" TO "anon";
GRANT SELECT("full_name") ON TABLE "public"."profiles" TO "authenticated";



GRANT ALL ON TABLE "public"."purchases" TO "anon";
GRANT ALL ON TABLE "public"."purchases" TO "authenticated";
GRANT ALL ON TABLE "public"."purchases" TO "service_role";



GRANT ALL ON TABLE "public"."reviews" TO "anon";
GRANT ALL ON TABLE "public"."reviews" TO "authenticated";
GRANT ALL ON TABLE "public"."reviews" TO "service_role";



GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."reviews_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."tutorials" TO "anon";
GRANT ALL ON TABLE "public"."tutorials" TO "authenticated";
GRANT ALL ON TABLE "public"."tutorials" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
